---
title: "Tutorial reproducibility"
author: 
  - "Lars Vilhuber"
  - "Marie Connolly"
date: 3 January 2025
---

```{r config,include=FALSE}
library(readr)
library(here)
library(knitr)
library(dplyr)
library(ggplot2)
library(qualtRics)

# qualtRics secrets are read from the environment:
# - QUALTRICS_API_KEY
# - QUALTRICS_BASE_URL
# Let's check that they are there:

Sys.getenv("QUALTRICS_BASE_URL")


# Qualtrics data for Day 1:
# you can find this with all_surveys() %>% arrange(creationDate) %>% head()

QUALTRICS_DAY1 <- "SV_bBqbJ9cSSJdOBw2"

# Time when this was posted (discard anything before that)

QUALTRICS_DAY1_STIME <- "2025-01-02 09:00:00"

# Public Qualtrics URL for day 2

QUALTRICS_DAY2 <- "https://cornell.ca1.qualtrics.com/jfe/form/SV_3J9Z2Z2Z2Z2Z2Z2"

if (!dir.exists(here::here("data"))) {
  dir.create(here::here("data"))
}
```

::: {.panel-tabset}

## Follow along

[lars.vilhuber.com/p/assa2025/](https://lars.vilhuber.com/p/assa2025/)

## Survey on Background and Skills



## Day 1


- [Setting yourself up for reproducibility](https://larsvilhuber.github.io/day1-tutorial/)

## Survey for Day 2

<`r QUALTRICS_DAY2`>


## Day 2

One of the following (or a linear combination):

- [Reproducibility when some data are confidential](https://labordynamicsinstitute.github.io/reproducibility-confidential/) 
- [Advanced self-checking of reproducibility](https://larsvilhuber.github.io/self-checking-reproducibility/presentation/)


## Data

```{r downloaddata,include=FALSE}
# download data to local location

data.raw <- fetch_survey(surveyID = QUALTRICS_DAY1, verbose = TRUE) 
data <- data.raw |>
        filter(Status != "Survey Preview") |>
        filter(Consent == "I agree that my data will be used in the manner described.") |>
        filter(StartDate > QUALTRICS_DAY1_STIME) |>
  # renaming variables
  select(StartDate,EndDate,Status,Finished,RecordedDate,ResponseId,Consent,Degree,JEL_primary,
         starts_with("JEL_secondary"),starts_with("Desktop_"),starts_with("Advanced_usage_"),
         starts_with("Programming_"),starts_with("Versioning_"))


```

```{r create_table, results='asis'}
data |>
  select(Degree) |>
  group_by(Degree) |>
  summarise(Frequency=n()) |>
  ungroup() |>
  mutate(Percent = round(Frequency/nrow(data)*100,2)) -> data.table

data.table |> kable()

```


```{r, child=c(here::here('99-links.md'))}
```

:::

